/**
 * Created by zhoucaiguang on 2017/3/8.
 */
"use strict";
exports.dbConfigs = {
    server: 'localhost',
    user: "root",
    password: "root",
    database: "NodeJs",
    port: 3306,
    maxSockets: 10,
    timeout: 1,
    DB_PREFIX: 'node'
};
exports.configs = [
    {
        url: 'http://www.xiumm.cc',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['td img', 'img'],
        imagesKeyWordUrl: ['photo'],
        imagesAttr: ['src', 'href'],
        imagesType: ['png', 'jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['div.inline'],
        FolderNamRegExp: ["/\s/g", "/\//g"],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        imagesSavePath: __dirname + '/uploads/xiumm/',
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.html', 'photo'],
        notLikeKeyWord: ['#', 'javascript'],
        autoNext: false,
        autoLoop: false,
    },
    {
        url: 'http://www.xiuren.org',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.photoThum a'],
        imagesKeyWordUrl: ['.html'],
        imagesAttr: ['href'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['title'],
        FolderNamRegExp: ["/\s/g,/\//g", "/XiuRen.org/g", "/秀人网$/"],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.html'],
        notLikeKeyWord: ['#', 'javascript', 'download', 'Video', '108tv'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'http://www.umei.cc',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['#ArticleId0 img'],
        imagesKeyWordUrl: ['.htm'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['.ArticleTitle strong'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.htm', 'gangtai', 'gaoqing'],
        notLikeKeyWord: ['#', 'javascript', 'download', 'Video', '108tv'],
        autoNext: false,
        autoLoop: false,
    },
    {
        url: 'http://girl-atlas.net',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.slide img'],
        imagesKeyWordUrl: ['album'],
        imagesAttr: ['src', 'delay'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['.header-right h3'],
        FolderNamRegExp: ["/\s/g", "/\//g"],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['album'],
        notLikeKeyWord: ['#', 'javascript', 'display'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'http://www.beautyleg.com',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.table_all a'],
        imagesKeyWordUrl: ['show.php'],
        imagesAttr: ['href'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['title'],
        FolderNamRegExp: ["/\s/g", "/\//g"],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['photo'],
        notLikeKeyWord: ['#', 'javascript', 'jpg'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'http://www.beautylegmm.com',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.post a'],
        imagesKeyWordUrl: ['.html'],
        imagesAttr: ['href'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['.title h2'],
        FolderNamRegExp: ["/\s/g", "/\//g"],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.html'],
        notLikeKeyWord: ['#', 'javascript', 'jpg'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'http://www.rosmm.com',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['#imgString img'],
        imagesKeyWordUrl: ['.htm', 'rosimm'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: true,
        FolderNameElement: ['.title h1'],
        FolderNamRegExp: ["/\s/g", "/\//g"],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.htm'],
        notLikeKeyWord: ['#', 'javascript', 'jpg'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'http://www.177pic.info',
        isSort: true,
        base64: false,
        sortType: 'desc',
        imagesInfoElement: ['.entry-content img'],
        imagesKeyWordUrl: ['.html'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['.entry-title'],
        FolderNamRegExp: ["/\s/g", "/\//g"],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.html'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'zh-hant', 'zh-hans'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'http://www.jdlingyu.moe',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.main-body a'],
        imagesKeyWordUrl: ['jdlingyu'],
        imagesAttr: ['href'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['.main-title'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['jdlingyu'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'http://www.rayshen.com',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.pic-area img'],
        imagesKeyWordUrl: ['.html'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['title'],
        FolderNamRegExp: [/\s/g, /\//g, /上海睿奢文化传播有限公司/g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['rayshen'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://zippler.tuchong.com',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['zippler'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; version=mobile; webp_enabled=1; __utmt=1; token=5ed294ee28b94c07; __utma=115147160.989767144.1490252469.1490264583.1490273379.3; __utmb=115147160.43.10.1490273379; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g, /-图虫摄影网/g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['zippler.tuchong.com'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://tuchong.com/411015/',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['411015'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; version=mobile; webp_enabled=1; __utmt=1; token=5ed294ee28b94c07; __utma=115147160.989767144.1490252469.1490264583.1490273379.3; __utmb=115147160.43.10.1490273379; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['411015'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers', 'tags'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://madebai.tuchong.com/',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['madebai'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; webp_enabled=1; token=e642f7b6b51a0dc3; __utma=115147160.989767144.1490252469.1490252469.1490252469.1; __utmb=115147160.500.10.1490252469; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['madebai'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers', 'tags'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://gyeonlee.tuchong.com/',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['gyeonlee'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; webp_enabled=1; token=e642f7b6b51a0dc3; __utma=115147160.989767144.1490252469.1490252469.1490252469.1; __utmb=115147160.500.10.1490252469; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['gyeonlee'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers', 'tags'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://tuchong.com/267685/',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['267685'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; webp_enabled=1; token=e642f7b6b51a0dc3; __utma=115147160.989767144.1490252469.1490252469.1490252469.1; __utmb=115147160.500.10.1490252469; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['267685'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers', 'tags'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://tuchong.com/1001612/',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['1001612'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; webp_enabled=1; token=e642f7b6b51a0dc3; __utma=115147160.989767144.1490252469.1490252469.1490252469.1; __utmb=115147160.500.10.1490252469; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['1001612'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers', 'tags'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://huafox.tuchong.com/',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['huafox'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; webp_enabled=1; token=e642f7b6b51a0dc3; __utma=115147160.989767144.1490252469.1490252469.1490252469.1; __utmb=115147160.500.10.1490252469; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['huafox'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers', 'tags'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://tuchong.com/455975/',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['455975'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; webp_enabled=1; token=e642f7b6b51a0dc3; __utma=115147160.989767144.1490252469.1490252469.1490252469.1; __utmb=115147160.500.10.1490252469; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['455975'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers', 'tags'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'https://tuchong.com/1070868/',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.figures-wrapper img'],
        imagesKeyWordUrl: ['1070868'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png', 'thumb', 'php', 'page', 'followers'],
        isReturnDownload: false,
        headers: { Cookie: 'PHPSESSID=5uv89fp9c1mj84va2l7k9d63m1; webp_enabled=1; token=e642f7b6b51a0dc3; __utma=115147160.989767144.1490252469.1490252469.1490252469.1; __utmb=115147160.500.10.1490252469; __utmc=115147160; __utmz=115147160.1490252469.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic' },
        iSgb2312: false,
        FolderNameElement: ['meta[name="title"]'],
        FolderNameAttr: ['content'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['1070868'],
        notLikeKeyWord: ['#', 'javascript', 'jpg', 'png', 'albums', 'followers', 'tags'],
        autoNext: false,
        autoLoop: true,
    },
    {
        url: 'http://bcy.net',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.detail_clickable'],
        imagesKeyWordUrl: ['detail'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png'],
        isReturnDownload: false,
        headers: { Host: 'bcy.net', Connection: 'keep-alive', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': 1, 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', DNT: 1, Referer: "http://bcy.net/coser", 'Accept-Encoding': "gzip,deflate,sdch", 'Accept-Language': "zh-CN,zh;q=0.8", Cookie: "acw_tc=AQAAAFkUAn9CQQQAy8A2t0ryCX7tp5tO; PHPSESSID=3ctpoa25hd88e71c3nvfmejkr0; lang_set=zh; UM_distinctid=15b0601964e3ac-06ca498a41e063-1d3a6853-fa000-15b0601964f9a1; LOGGED_USER=Nn%2Flq9WmWx79eHT71Uf2byw%3D%3Ad2NnyjF654Y2u5RqI81PCA%3D%3D; mobile_set=no; CNZZDATA1257708097=1014489182-1490452282-null%7C1490534094; Hm_lvt_330d168f9714e3aa16c5661e62c00232=1490454419; Hm_lpvt_330d168f9714e3aa16c5661e62c00232=1490538074" },
        iSgb2312: false,
        FolderNameElement: ['.js-post-title'],
        FolderNameAttr: ['text'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['coser', 'expo'],
        notLikeKeyWord: ['#', 'javascript', 'novel', 'illust', 'tags', '.apk', 'static', 'p='],
        autoNext: false,
        autoLoop: true,
        iSGzip: true,
        urlType: true,
    },
    {
        url: 'http://www.zrmm.com',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['#picture img'],
        imagesKeyWordUrl: ['article'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png'],
        isReturnDownload: false,
        headers: {},
        iSgb2312: false,
        FolderNameElement: ['.metaRight h2 a'],
        FolderNameAttr: ['text'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['zrmm'],
        notLikeKeyWord: ['#', 'javascript', 'xml'],
        autoNext: false,
        autoLoop: true,
        iSGzip: false,
        urlType: true,
    }
];
