/**
 * Created by zhoucaiguang on 2017/3/8.
 */
"use strict";
exports.dbConfigs = {
    server: 'localhost',
    user: "root",
    password: "root",
    database: "NodeJs",
    port: 3306,
    maxSockets: 10,
    timeout: 1,
    DB_PREFIX: 'node'
};
exports.configs = [
    {
        url: 'http://www.xiumm.cc',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['td img', 'img'],
        imagesKeyWordUrl: ['photo'],
        imagesAttr: ['src', 'href'],
        imagesType: ['png', 'jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['div.inline'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        imagesSavePath: __dirname + '/uploads/xiumm/',
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.html', 'photo'],
        notLikeKeyWord: ['#', 'javascript'],
        autoNext: false,
        autoLoop: false,
    },
    {
        url: 'http://www.xiuren.org',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.photoThum a'],
        imagesKeyWordUrl: ['.html'],
        imagesAttr: ['href'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['title'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.html'],
        notLikeKeyWord: ['#', 'javascript', 'download', 'Video', '108tv'],
        autoNext: false,
        autoLoop: false,
    },
    {
        url: 'http://www.umei.cc',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['#ArticleId0 img'],
        imagesKeyWordUrl: ['.htm'],
        imagesAttr: ['src'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['.ArticleTitle strong'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['.htm', 'gangtai', 'gaoqing'],
        notLikeKeyWord: ['#', 'javascript', 'download', 'Video', '108tv'],
        autoNext: false,
        autoLoop: false,
    },
    {
        url: 'http://girl-atlas.net/album/576545e158e039318beb3909',
        isSort: true,
        base64: false,
        sortType: 'asc',
        imagesInfoElement: ['.slide img'],
        imagesKeyWordUrl: ['album'],
        imagesAttr: ['src', 'delay'],
        imagesType: ['jpg'],
        imagesNotDownload: ['logo.png', 'pixel.png'],
        isReturnDownload: false,
        headers: { Referer: '' },
        iSgb2312: false,
        FolderNameElement: ['.header-right h3'],
        FolderNamRegExp: [/\s/g, /\//g],
        timeout: 4000,
        urlTimeout: 4000,
        imgTimeout: 5000,
        isResetDownImage: false,
        urlElement: ['a'],
        urlAttr: ['href'],
        likeKeyWord: ['album', '576545ed58e039318beb3c0b'],
        notLikeKeyWord: ['#', 'javascript', 'display'],
        autoNext: false,
        autoLoop: false,
    }
];
